# Generated by Django 3.1.2 on 2020-10-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Date',
            field=models.DateField(default='SOME STRING', max_length=30),
        ),
        migrations.AddField(
            model_name='news',
            name='Details',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='Id',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='Newsfrom',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='news',
            name='URLofnews',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='Title',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
    ]
