# Generated by Django 3.1.2 on 2020-10-11 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20201010_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
