# Generated by Django 3.1.2 on 2020-10-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20201011_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='Date',
        ),
    ]
